UAndes.ICC5103.202301/Models/Multipropietario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multipropietario
    {
        public int Id { get; set; }
        public string Comuna { get; set; }
        public string Manzana { get; set; }
        public string RolPredial { get; set; }
        public string RutPropietario { get; set; }
        public string PorcentajeDerechoPropietario { get; set; }
        public string Foja { get; set; }
        public Nullable<int> AnoInscripcion { get; set; }
        public string NumeroInscripcion { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public int AnoVigenciaInicial { get; set; }
        public Nullable<int> AnoVigenciaFinal { get; set; }
    }
}

UAndes.ICC5103.202301/Controllers/MultipropietariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UAndes.ICC5103._202301.Models;

namespace UAndes.ICC5103._202301.Controllers
{
    public class MultipropietariosController : Controller
    {
        private readonly InscripcionesBrDbEntities db = new InscripcionesBrDbEntities();

        // GET: Multipropietarios
        public ActionResult Index(string comuna, string manzana, string predio, string ano)
        {

            comuna = comuna ?? "";
            manzana = manzana ?? "";
            predio = predio ?? "";
            ano = ano ?? "";

            var listaComunas = new Comuna();

            List<string> comunas = listaComunas.ListaDeComunas();

            ViewBag.comunas = comunas;

            if (string.IsNullOrEmpty(comuna) && string.IsNullOrEmpty(manzana) && string.IsNullOrEmpty(predio) && string.IsNullOrEmpty(ano))
            {
                return View(db.Multipropietario.ToList());
            }

            int anoProcesado = 0;
            if (String.IsNullOrEmpty(ano) != true)
            {
                anoProcesado = int.Parse(ano);
            }

            List<Multipropietario> multipropietariosBusqueda = db.Multipropietario.Where(item =>
                                            (item.Comuna == comuna || string.IsNullOrEmpty(comuna)) &&
                                            (item.Manzana == manzana.ToString() || string.IsNullOrEmpty(manzana)) &&
                                            (item.RolPredial == predio.ToString() || string.IsNullOrEmpty(predio)) &&
                                            (item.AnoVigenciaFinal == anoProcesado || string.IsNullOrEmpty(ano))
                                            ).ToList();

            if (multipropietariosBusqueda.Count > 0)
            {
                return View(multipropietariosBusqueda);
            }
            else
            {
                List<Multipropietario> multipropietariosVigentes = db.Multipropietario.Where(item =>
                                            (item.Comuna == comuna || string.IsNullOrEmpty(comuna)) &&
                                            (item.Manzana == manzana.ToString() || string.IsNullOrEmpty(manzana)) &&
                                            (item.RolPredial == predio.ToString() || string.IsNullOrEmpty(predio)) &&
                                            (item.AnoVigenciaInicial >= anoProcesado) &&
                                            (item.AnoVigenciaFinal == null)
                                            ).ToList();

              
                return View(multipropietariosVigentes);
            }
        }

        // GET: Multipropietarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Multipropietario multipropietario = db.Multipropietario.Find(id);
            if (multipropietario == null)
            {
                return HttpNotFound();
            }
            return View(multipropietario);
        }

        // GET: Multipropietarios/Create
        public ActionResult Create()
        {
            var comuna2 = new Comuna();

            List<string> comunas2 = comuna2.ListaDeComunas();

            ViewBag.comunas = comunas2;

            return View();
        }

        // POST: Multipropietarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Comuna,Manzana,RolPredial,RutPropietario,PorcentajeDerechoPropietario,Foja,AnoInscripcion,NumeroInscripcion,FechaInscripcion,AnoVigenciaInicial,AnoVigenciaFinal")] Multipropietario multipropietario)
        {
            if (ModelState.IsValid)
            {
                db.Multipropietario.Add(multipropietario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(multipropietario);
        }

        // GET: Multipropietarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Multipropietario multipropietario = db.Multipropietario.Find(id);
            if (multipropietario == null)
            {
                return HttpNotFound();
            }
            return View(multipropietario);
        }

        // POST: Multipropietarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Comuna,Manzana,RolPredial,RutPropietario,PorcentajeDerechoPropietario,Foja,AnoInscripcion,NumeroInscripcion,FechaInscripcion,AnoVigenciaInicial,AnoVigenciaFinal")] Multipropietario multipropietario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(multipropietario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(multipropietario);
        }

        // GET: Multipropietarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Multipropietario multipropietario = db.Multipropietario.Find(id);
            if (multipropietario == null)
            {
                return HttpNotFound();
            }
            return View(multipropietario);
        }

        // POST: Multipropietarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Multipropietario multipropietario = db.Multipropietario.Find(id);
            db.Multipropietario.Remove(multipropietario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UAndes.ICC5103.202301/Views/Multipropietarios/Create.cshtml
@model UAndes.ICC5103._202301.Models.Multipropietario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Multipropietario</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.RutPropietario, "Rut del Propietario", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RutPropietario, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese Rut", @required = "required" } })
            @Html.ValidationMessageFor(model => model.RutPropietario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Comuna, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Comuna, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese Comuna", @required = "required" } })
            @Html.ValidationMessageFor(model => model.Comuna, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Manzana, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Manzana, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese Manzana", @required = "required" } })
            @Html.ValidationMessageFor(model => model.Manzana, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RolPredial, "Predio", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RolPredial, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese Predio", @required = "required" } })
            @Html.ValidationMessageFor(model => model.RolPredial, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.PorcentajeDerechoPropietario, "Porcentaje de Derechos", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PorcentajeDerechoPropietario, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese Porcentaje %", @required = "required" } })
            @Html.ValidationMessageFor(model => model.PorcentajeDerechoPropietario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Foja, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Foja, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese Foja", @required = "required" } })
            @Html.ValidationMessageFor(model => model.Foja, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnoInscripcion, "Año de Inscripcion", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AnoInscripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese año", @required = "required" } })
            @Html.ValidationMessageFor(model => model.AnoInscripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumeroInscripcion, "Numero de Inscripcion", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumeroInscripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese Numero de Inscripcion", @required = "required" } })
            @Html.ValidationMessageFor(model => model.NumeroInscripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FechaInscripcion, "Fecha de Inscripcion", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FechaInscripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "dd/mm/año", @required = "required" } })
            @Html.ValidationMessageFor(model => model.FechaInscripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnoVigenciaInicial, "Año Vigencia Inicial", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AnoVigenciaInicial, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese año", @required = "required" } })
            @Html.ValidationMessageFor(model => model.AnoVigenciaInicial, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnoVigenciaFinal, "Año Vigencia Final", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AnoVigenciaFinal, new { htmlAttributes = new { @class = "form-control", placeholder = "Ingrese año", @required = "required" } })
            @Html.ValidationMessageFor(model => model.AnoVigenciaFinal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UAndes.ICC5103.202301/Views/Multipropietarios/Delete.cshtml
@model UAndes.ICC5103._202301.Models.Multipropietario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Multipropietario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Comuna)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comuna)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manzana)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manzana)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RolPredial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RolPredial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RutPropietario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RutPropietario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PorcentajeDerechoPropietario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PorcentajeDerechoPropietario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoInscripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoInscripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroInscripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroInscripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInscripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInscripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoVigenciaInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoVigenciaInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoVigenciaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoVigenciaFinal)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UAndes.ICC5103.202301/Views/Multipropietarios/Details.cshtml
@model UAndes.ICC5103._202301.Models.Multipropietario

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Multipropietario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Comuna)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comuna)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manzana)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manzana)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RolPredial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RolPredial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RutPropietario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RutPropietario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PorcentajeDerechoPropietario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PorcentajeDerechoPropietario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoInscripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoInscripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroInscripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroInscripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInscripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInscripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoVigenciaInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoVigenciaInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoVigenciaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoVigenciaFinal)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UAndes.ICC5103.202301/Views/Multipropietarios/Edit.cshtml
@model UAndes.ICC5103._202301.Models.Multipropietario

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Multipropietario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Comuna, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comuna, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comuna, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manzana, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manzana, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manzana, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RolPredial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RolPredial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RolPredial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RutPropietario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RutPropietario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RutPropietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PorcentajeDerechoPropietario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PorcentajeDerechoPropietario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PorcentajeDerechoPropietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Foja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnoInscripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnoInscripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnoInscripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroInscripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroInscripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroInscripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaInscripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaInscripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaInscripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnoVigenciaInicial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnoVigenciaInicial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnoVigenciaInicial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnoVigenciaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnoVigenciaFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnoVigenciaFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UAndes.ICC5103.202301/Views/Multipropietarios/Index.cshtml
@model IEnumerable<UAndes.ICC5103._202301.Models.Multipropietario>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Multipropietarios", FormMethod.Get))
{
    <div class="form-group">
        <b> Opciones de busqueda: </b>
        @Html.DropDownList("comuna", new SelectList(ViewBag.comunas), "Comuna", new { @class = "form-control" })


        @Html.Editor("manzana", new { htmlAttributes = new { @class = "form-control", placeholder = "manzana" } })
        @Html.Editor("predio", new { htmlAttributes = new { @class = "form-control", placeholder = "predio" } })
        @Html.Editor("ano", new { htmlAttributes = new { @class = "form-control", placeholder = "año" } })
        <input type="submit" name="submit" value="Search" />
    </div>
    


    
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Comuna)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manzana)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RolPredial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RutPropietario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PorcentajeDerechoPropietario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnoInscripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroInscripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaInscripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnoVigenciaInicial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnoVigenciaFinal)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Comuna)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Manzana)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RolPredial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RutPropietario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PorcentajeDerechoPropietario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Foja)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AnoInscripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumeroInscripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaInscripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AnoVigenciaInicial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AnoVigenciaFinal)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id
                }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id
}) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
        }

</table>